Jest Reporting?

diff --git a/.github/workflows/master_ranksterr-app-dev.yml b/.github/workflows/master_ranksterr-app-dev.yml
--- a/.github/workflows/master_ranksterr-app-dev.yml
+++ b/.github/workflows/master_ranksterr-app-dev.yml
@@ -15,9 +15,36 @@ jobs:
     
     permissions:
       checks: write  # Add this line to grant write permission for checks
+      contents: read
+      actions: read
     
     steps:
       - uses: actions/checkout@v4
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16.x'  # Specify the Node.js version you need
+
+      - name: Run Nextjs npm script
+        run: |
+          cd ranksterr-next-app 
+          npm install      
+          npm run testJunit
+          npm run build        
+
+      - name: Test Jest Junit Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports/jest-*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
+          fail-on-error: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+        
+      
+      
       - name: Set up .NET Core
         uses: actions/setup-dotnet@v1
         with:
@@ -46,18 +73,12 @@ jobs:
           fail-on-error: true
           token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '16.x'  # Specify the Node.js version you need
-
       - name: Run npm script
         run: |
           cd ranksterr-react-app 
           npm install      
           npm run test
           npm run buildlinux
-          
             
       - name: Write secret to config file
         env:
